// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package grpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import empty "github.com/golang/protobuf/ptypes/empty"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// A plugin resource
type PluginData struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CdnLink              string   `protobuf:"bytes,2,opt,name=cdn_link,json=cdnLink,proto3" json:"cdn_link,omitempty"`
	Status               string   `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PluginData) Reset()         { *m = PluginData{} }
func (m *PluginData) String() string { return proto.CompactTextString(m) }
func (*PluginData) ProtoMessage()    {}
func (*PluginData) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_a969bb17ff64ca59, []int{0}
}
func (m *PluginData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PluginData.Unmarshal(m, b)
}
func (m *PluginData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PluginData.Marshal(b, m, deterministic)
}
func (dst *PluginData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PluginData.Merge(dst, src)
}
func (m *PluginData) XXX_Size() int {
	return xxx_messageInfo_PluginData.Size(m)
}
func (m *PluginData) XXX_DiscardUnknown() {
	xxx_messageInfo_PluginData.DiscardUnknown(m)
}

var xxx_messageInfo_PluginData proto.InternalMessageInfo

func (m *PluginData) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PluginData) GetCdnLink() string {
	if m != nil {
		return m.CdnLink
	}
	return ""
}

func (m *PluginData) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

// Request message for CreatePlugin method
type CreatePluginRequest struct {
	Plugin               *PluginData `protobuf:"bytes,1,opt,name=plugin,proto3" json:"plugin,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *CreatePluginRequest) Reset()         { *m = CreatePluginRequest{} }
func (m *CreatePluginRequest) String() string { return proto.CompactTextString(m) }
func (*CreatePluginRequest) ProtoMessage()    {}
func (*CreatePluginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_a969bb17ff64ca59, []int{1}
}
func (m *CreatePluginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePluginRequest.Unmarshal(m, b)
}
func (m *CreatePluginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePluginRequest.Marshal(b, m, deterministic)
}
func (dst *CreatePluginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePluginRequest.Merge(dst, src)
}
func (m *CreatePluginRequest) XXX_Size() int {
	return xxx_messageInfo_CreatePluginRequest.Size(m)
}
func (m *CreatePluginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePluginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePluginRequest proto.InternalMessageInfo

func (m *CreatePluginRequest) GetPlugin() *PluginData {
	if m != nil {
		return m.Plugin
	}
	return nil
}

// Request message for GetPlugin method
type GetPluginRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPluginRequest) Reset()         { *m = GetPluginRequest{} }
func (m *GetPluginRequest) String() string { return proto.CompactTextString(m) }
func (*GetPluginRequest) ProtoMessage()    {}
func (*GetPluginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_a969bb17ff64ca59, []int{2}
}
func (m *GetPluginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPluginRequest.Unmarshal(m, b)
}
func (m *GetPluginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPluginRequest.Marshal(b, m, deterministic)
}
func (dst *GetPluginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPluginRequest.Merge(dst, src)
}
func (m *GetPluginRequest) XXX_Size() int {
	return xxx_messageInfo_GetPluginRequest.Size(m)
}
func (m *GetPluginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPluginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPluginRequest proto.InternalMessageInfo

func (m *GetPluginRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

// Request message for DeletePlugin method
type DeletePluginRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeletePluginRequest) Reset()         { *m = DeletePluginRequest{} }
func (m *DeletePluginRequest) String() string { return proto.CompactTextString(m) }
func (*DeletePluginRequest) ProtoMessage()    {}
func (*DeletePluginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_a969bb17ff64ca59, []int{3}
}
func (m *DeletePluginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeletePluginRequest.Unmarshal(m, b)
}
func (m *DeletePluginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeletePluginRequest.Marshal(b, m, deterministic)
}
func (dst *DeletePluginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeletePluginRequest.Merge(dst, src)
}
func (m *DeletePluginRequest) XXX_Size() int {
	return xxx_messageInfo_DeletePluginRequest.Size(m)
}
func (m *DeletePluginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeletePluginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeletePluginRequest proto.InternalMessageInfo

func (m *DeletePluginRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func init() {
	proto.RegisterType((*PluginData)(nil), "grpc.PluginData")
	proto.RegisterType((*CreatePluginRequest)(nil), "grpc.CreatePluginRequest")
	proto.RegisterType((*GetPluginRequest)(nil), "grpc.GetPluginRequest")
	proto.RegisterType((*DeletePluginRequest)(nil), "grpc.DeletePluginRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GrpcClient is the client API for Grpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GrpcClient interface {
	// Creates a new plugin
	CreatePlugin(ctx context.Context, in *CreatePluginRequest, opts ...grpc.CallOption) (*PluginData, error)
	// Get plugin with specific id
	GetPlugin(ctx context.Context, in *GetPluginRequest, opts ...grpc.CallOption) (*PluginData, error)
	// Delete stored plugin
	DeletePlugin(ctx context.Context, in *DeletePluginRequest, opts ...grpc.CallOption) (*empty.Empty, error)
}

type grpcClient struct {
	cc *grpc.ClientConn
}

func NewGrpcClient(cc *grpc.ClientConn) GrpcClient {
	return &grpcClient{cc}
}

func (c *grpcClient) CreatePlugin(ctx context.Context, in *CreatePluginRequest, opts ...grpc.CallOption) (*PluginData, error) {
	out := new(PluginData)
	err := c.cc.Invoke(ctx, "/grpc.Grpc/CreatePlugin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grpcClient) GetPlugin(ctx context.Context, in *GetPluginRequest, opts ...grpc.CallOption) (*PluginData, error) {
	out := new(PluginData)
	err := c.cc.Invoke(ctx, "/grpc.Grpc/GetPlugin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grpcClient) DeletePlugin(ctx context.Context, in *DeletePluginRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/grpc.Grpc/DeletePlugin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GrpcServer is the server API for Grpc service.
type GrpcServer interface {
	// Creates a new plugin
	CreatePlugin(context.Context, *CreatePluginRequest) (*PluginData, error)
	// Get plugin with specific id
	GetPlugin(context.Context, *GetPluginRequest) (*PluginData, error)
	// Delete stored plugin
	DeletePlugin(context.Context, *DeletePluginRequest) (*empty.Empty, error)
}

func RegisterGrpcServer(s *grpc.Server, srv GrpcServer) {
	s.RegisterService(&_Grpc_serviceDesc, srv)
}

func _Grpc_CreatePlugin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePluginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcServer).CreatePlugin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Grpc/CreatePlugin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcServer).CreatePlugin(ctx, req.(*CreatePluginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Grpc_GetPlugin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPluginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcServer).GetPlugin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Grpc/GetPlugin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcServer).GetPlugin(ctx, req.(*GetPluginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Grpc_DeletePlugin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePluginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcServer).DeletePlugin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Grpc/DeletePlugin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcServer).DeletePlugin(ctx, req.(*DeletePluginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Grpc_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.Grpc",
	HandlerType: (*GrpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePlugin",
			Handler:    _Grpc_CreatePlugin_Handler,
		},
		{
			MethodName: "GetPlugin",
			Handler:    _Grpc_GetPlugin_Handler,
		},
		{
			MethodName: "DeletePlugin",
			Handler:    _Grpc_DeletePlugin_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}

func init() { proto.RegisterFile("service.proto", fileDescriptor_service_a969bb17ff64ca59) }

var fileDescriptor_service_a969bb17ff64ca59 = []byte{
	// 331 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0xc1, 0x4e, 0xf2, 0x40,
	0x10, 0xc7, 0x43, 0x3f, 0xc2, 0x27, 0x03, 0x1a, 0x32, 0x68, 0x53, 0x0a, 0x07, 0xb3, 0x89, 0x09,
	0xf1, 0xd0, 0x46, 0xbc, 0x79, 0xf1, 0x20, 0x86, 0x8b, 0x09, 0x86, 0x93, 0x37, 0xb2, 0xb4, 0x6b,
	0xb3, 0xa1, 0x6e, 0x6b, 0x77, 0x4b, 0x62, 0x0c, 0x17, 0x1f, 0x41, 0x1f, 0xcd, 0x57, 0xf0, 0x41,
	0x0c, 0xbb, 0x45, 0xa1, 0xf6, 0xd6, 0xce, 0x7f, 0xf6, 0x37, 0xbf, 0xc9, 0xc0, 0xa1, 0x64, 0xd9,
	0x8a, 0x07, 0xcc, 0x4b, 0xb3, 0x44, 0x25, 0x58, 0x8f, 0xb2, 0x34, 0x70, 0xfb, 0x51, 0x92, 0x44,
	0x31, 0xf3, 0x75, 0x6d, 0x91, 0x3f, 0xfa, 0xec, 0x29, 0x55, 0x2f, 0xa6, 0xc5, 0x1d, 0x14, 0x21,
	0x4d, 0xb9, 0x4f, 0x85, 0x48, 0x14, 0x55, 0x3c, 0x11, 0xd2, 0xa4, 0x64, 0x0a, 0x70, 0x1f, 0xe7,
	0x11, 0x17, 0x63, 0xaa, 0x28, 0x1e, 0x81, 0xc5, 0x43, 0xa7, 0x76, 0x5a, 0x1b, 0x36, 0x67, 0x16,
	0x0f, 0xb1, 0x07, 0x07, 0x41, 0x28, 0xe6, 0x31, 0x17, 0x4b, 0xc7, 0xd2, 0xd5, 0xff, 0x41, 0x28,
	0xee, 0xb8, 0x58, 0xa2, 0x0d, 0x0d, 0xa9, 0xa8, 0xca, 0xa5, 0xf3, 0x4f, 0x07, 0xc5, 0x1f, 0xb9,
	0x86, 0xee, 0x4d, 0xc6, 0xa8, 0x62, 0x06, 0x3b, 0x63, 0xcf, 0x39, 0x93, 0x0a, 0x87, 0xd0, 0x48,
	0x75, 0x41, 0xd3, 0x5b, 0xa3, 0x8e, 0xb7, 0x31, 0xf7, 0x7e, 0x67, 0xcf, 0x8a, 0x9c, 0x10, 0xe8,
	0x4c, 0x98, 0xda, 0x7f, 0x5d, 0xf2, 0x22, 0x67, 0xd0, 0x1d, 0xb3, 0x98, 0x95, 0x87, 0x94, 0xda,
	0x46, 0xef, 0x16, 0xd4, 0x27, 0x59, 0x1a, 0xe0, 0x03, 0xb4, 0x77, 0xa5, 0xb0, 0x67, 0xa6, 0x57,
	0x88, 0xba, 0x7f, 0xc4, 0x48, 0xff, 0xed, 0xf3, 0xeb, 0xc3, 0x3a, 0x21, 0x2d, 0x7f, 0x75, 0xe1,
	0x1b, 0x49, 0x79, 0x55, 0xd8, 0xe2, 0x14, 0x9a, 0x3f, 0xb6, 0x68, 0x9b, 0xb7, 0x65, 0xfd, 0x0a,
	0xa6, 0xa3, 0x99, 0x88, 0x9d, 0x1d, 0xa6, 0xff, 0xca, 0xc3, 0x35, 0xce, 0xa1, 0xbd, 0xbb, 0xda,
	0x56, 0xb5, 0x62, 0x5d, 0xd7, 0xf6, 0xcc, 0x69, 0xbd, 0xed, 0xdd, 0xbd, 0xdb, 0xcd, 0xdd, 0xc9,
	0x40, 0xc3, 0xed, 0xf3, 0xe3, 0x3d, 0xb8, 0xf9, 0x58, 0x2f, 0x1a, 0xba, 0xfb, 0xf2, 0x3b, 0x00,
	0x00, 0xff, 0xff, 0xcc, 0x04, 0x0b, 0x83, 0x4a, 0x02, 0x00, 0x00,
}
