// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: rest_template.proto

package restmodel

import (
	fmt "fmt"
	math "math"

	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

// Template holds the data that will be generated
type Template struct {
	// Name of generated file
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Encoding of generated tar file
	TarFile              string   `protobuf:"bytes,6,opt,name=tar_file,json=tarFile,proto3" json:"tar_file,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Template) Reset()         { *m = Template{} }
func (m *Template) String() string { return proto.CompactTextString(m) }
func (*Template) ProtoMessage()    {}
func (*Template) Descriptor() ([]byte, []int) {
	return fileDescriptor_906eeb233f791505, []int{0}
}
func (m *Template) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Template.Unmarshal(m, b)
}
func (m *Template) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Template.Marshal(b, m, deterministic)
}
func (m *Template) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Template.Merge(m, src)
}
func (m *Template) XXX_Size() int {
	return xxx_messageInfo_Template.Size(m)
}
func (m *Template) XXX_DiscardUnknown() {
	xxx_messageInfo_Template.DiscardUnknown(m)
}

var xxx_messageInfo_Template proto.InternalMessageInfo

func (m *Template) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Template) GetTarFile() string {
	if m != nil {
		return m.TarFile
	}
	return ""
}

func (*Template) XXX_MessageName() string {
	return "restmodel.Template"
}
func init() {
	proto.RegisterType((*Template)(nil), "restmodel.Template")
}

func init() { proto.RegisterFile("rest_template.proto", fileDescriptor_906eeb233f791505) }

var fileDescriptor_906eeb233f791505 = []byte{
	// 143 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2e, 0x4a, 0x2d, 0x2e,
	0x89, 0x2f, 0x49, 0xcd, 0x2d, 0xc8, 0x49, 0x2c, 0x49, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17,
	0xe2, 0x04, 0x09, 0xe6, 0xe6, 0xa7, 0xa4, 0xe6, 0x48, 0xe9, 0xa6, 0x67, 0x96, 0x64, 0x94, 0x26,
	0xe9, 0x25, 0xe7, 0xe7, 0xea, 0xa7, 0xe7, 0xa7, 0xe7, 0xeb, 0x83, 0x55, 0x24, 0x95, 0xa6, 0x81,
	0x79, 0x60, 0x0e, 0x98, 0x05, 0xd1, 0xa9, 0x64, 0xc9, 0xc5, 0x11, 0x02, 0x35, 0x4b, 0x48, 0x88,
	0x8b, 0x25, 0x2f, 0x31, 0x37, 0x55, 0x82, 0x51, 0x81, 0x51, 0x83, 0x33, 0x08, 0xcc, 0x16, 0x92,
	0xe4, 0xe2, 0x28, 0x49, 0x2c, 0x8a, 0x4f, 0xcb, 0xcc, 0x49, 0x95, 0x60, 0x03, 0x8b, 0xb3, 0x97,
	0x24, 0x16, 0xb9, 0x65, 0xe6, 0xa4, 0x3a, 0xb1, 0x9c, 0x78, 0x2c, 0xc7, 0x98, 0xc4, 0x06, 0x36,
	0xc7, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0xaf, 0x04, 0x3e, 0x10, 0x98, 0x00, 0x00, 0x00,
}
