// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: project.proto

package model

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

// A plugin resource
type Plugin struct {
	PluginName           string   `protobuf:"bytes,1,opt,name=pluginName,proto3" json:"pluginName,omitempty"`
	Id                   int32    `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Selected             bool     `protobuf:"varint,3,opt,name=selected,proto3" json:"selected,omitempty"`
	Port                 int32    `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Plugin) Reset()         { *m = Plugin{} }
func (m *Plugin) String() string { return proto.CompactTextString(m) }
func (*Plugin) ProtoMessage()    {}
func (*Plugin) Descriptor() ([]byte, []int) {
	return fileDescriptor_8340e6318dfdfac2, []int{0}
}
func (m *Plugin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Plugin.Unmarshal(m, b)
}
func (m *Plugin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Plugin.Marshal(b, m, deterministic)
}
func (m *Plugin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Plugin.Merge(m, src)
}
func (m *Plugin) XXX_Size() int {
	return xxx_messageInfo_Plugin.Size(m)
}
func (m *Plugin) XXX_DiscardUnknown() {
	xxx_messageInfo_Plugin.DiscardUnknown(m)
}

var xxx_messageInfo_Plugin proto.InternalMessageInfo

func (m *Plugin) GetPluginName() string {
	if m != nil {
		return m.PluginName
	}
	return ""
}

func (m *Plugin) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Plugin) GetSelected() bool {
	if m != nil {
		return m.Selected
	}
	return false
}

func (m *Plugin) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (*Plugin) XXX_MessageName() string {
	return "model.Plugin"
}

// A custom plugin resource
type CustomPlugin struct {
	CustomPluginName     string   `protobuf:"bytes,1,opt,name=customPluginName,proto3" json:"customPluginName,omitempty"`
	PackageName          string   `protobuf:"bytes,2,opt,name=packageName,proto3" json:"packageName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CustomPlugin) Reset()         { *m = CustomPlugin{} }
func (m *CustomPlugin) String() string { return proto.CompactTextString(m) }
func (*CustomPlugin) ProtoMessage()    {}
func (*CustomPlugin) Descriptor() ([]byte, []int) {
	return fileDescriptor_8340e6318dfdfac2, []int{1}
}
func (m *CustomPlugin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CustomPlugin.Unmarshal(m, b)
}
func (m *CustomPlugin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CustomPlugin.Marshal(b, m, deterministic)
}
func (m *CustomPlugin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CustomPlugin.Merge(m, src)
}
func (m *CustomPlugin) XXX_Size() int {
	return xxx_messageInfo_CustomPlugin.Size(m)
}
func (m *CustomPlugin) XXX_DiscardUnknown() {
	xxx_messageInfo_CustomPlugin.DiscardUnknown(m)
}

var xxx_messageInfo_CustomPlugin proto.InternalMessageInfo

func (m *CustomPlugin) GetCustomPluginName() string {
	if m != nil {
		return m.CustomPluginName
	}
	return ""
}

func (m *CustomPlugin) GetPackageName() string {
	if m != nil {
		return m.PackageName
	}
	return ""
}

func (*CustomPlugin) XXX_MessageName() string {
	return "model.CustomPlugin"
}

// Project holds the data fields stored
type Project struct {
	ProjectName          string          `protobuf:"bytes,1,opt,name=projectName,proto3" json:"projectName,omitempty"`
	Plugin               []*Plugin       `protobuf:"bytes,2,rep,name=plugin,proto3" json:"plugin,omitempty"`
	AgentName            string          `protobuf:"bytes,3,opt,name=agentName,proto3" json:"agentName,omitempty"`
	CustomPlugin         []*CustomPlugin `protobuf:"bytes,4,rep,name=customPlugin,proto3" json:"customPlugin,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Project) Reset()         { *m = Project{} }
func (m *Project) String() string { return proto.CompactTextString(m) }
func (*Project) ProtoMessage()    {}
func (*Project) Descriptor() ([]byte, []int) {
	return fileDescriptor_8340e6318dfdfac2, []int{2}
}
func (m *Project) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Project.Unmarshal(m, b)
}
func (m *Project) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Project.Marshal(b, m, deterministic)
}
func (m *Project) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Project.Merge(m, src)
}
func (m *Project) XXX_Size() int {
	return xxx_messageInfo_Project.Size(m)
}
func (m *Project) XXX_DiscardUnknown() {
	xxx_messageInfo_Project.DiscardUnknown(m)
}

var xxx_messageInfo_Project proto.InternalMessageInfo

func (m *Project) GetProjectName() string {
	if m != nil {
		return m.ProjectName
	}
	return ""
}

func (m *Project) GetPlugin() []*Plugin {
	if m != nil {
		return m.Plugin
	}
	return nil
}

func (m *Project) GetAgentName() string {
	if m != nil {
		return m.AgentName
	}
	return ""
}

func (m *Project) GetCustomPlugin() []*CustomPlugin {
	if m != nil {
		return m.CustomPlugin
	}
	return nil
}

func (*Project) XXX_MessageName() string {
	return "model.Project"
}
func init() {
	proto.RegisterType((*Plugin)(nil), "model.Plugin")
	proto.RegisterType((*CustomPlugin)(nil), "model.CustomPlugin")
	proto.RegisterType((*Project)(nil), "model.Project")
}

func init() { proto.RegisterFile("project.proto", fileDescriptor_8340e6318dfdfac2) }

var fileDescriptor_8340e6318dfdfac2 = []byte{
	// 272 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x51, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x65, 0x93, 0x34, 0xb6, 0xd3, 0x56, 0x64, 0xbc, 0x2c, 0x45, 0x4a, 0x08, 0x08, 0x41, 0x30,
	0x05, 0x3d, 0x78, 0xd7, 0xbb, 0x94, 0x3d, 0x7b, 0x49, 0x36, 0xeb, 0x36, 0x9a, 0x74, 0x97, 0x74,
	0xf3, 0x51, 0xfe, 0x89, 0xff, 0xe1, 0x8f, 0x08, 0xb3, 0x41, 0x57, 0xbc, 0xbd, 0xf7, 0xe6, 0xe5,
	0xbd, 0xcc, 0x2c, 0xac, 0xed, 0x60, 0xde, 0x94, 0x74, 0xa5, 0x1d, 0x8c, 0x33, 0x38, 0xeb, 0x4d,
	0xa3, 0xba, 0xcd, 0xad, 0x6e, 0xdd, 0x61, 0xac, 0x4b, 0x69, 0xfa, 0x9d, 0x36, 0xda, 0xec, 0x68,
	0x5a, 0x8f, 0xaf, 0xc4, 0x88, 0x10, 0xf2, 0x5f, 0xe5, 0x07, 0x48, 0xf7, 0xdd, 0xa8, 0xdb, 0x23,
	0x6e, 0x01, 0x2c, 0xa1, 0xe7, 0xaa, 0x57, 0x9c, 0x65, 0xac, 0x58, 0x88, 0x40, 0xc1, 0x73, 0x88,
	0xda, 0x86, 0x47, 0x19, 0x2b, 0x66, 0x22, 0x6a, 0x1b, 0xdc, 0xc0, 0xfc, 0xa4, 0x3a, 0x25, 0x9d,
	0x6a, 0x78, 0x9c, 0xb1, 0x62, 0x2e, 0x7e, 0x38, 0x22, 0x24, 0xd6, 0x0c, 0x8e, 0x27, 0xe4, 0x26,
	0x9c, 0xbf, 0xc0, 0xea, 0x69, 0x3c, 0x39, 0xd3, 0x4f, 0x7d, 0x37, 0x70, 0x21, 0x03, 0x1e, 0xb4,
	0xfe, 0xd3, 0x31, 0x83, 0xa5, 0xad, 0xe4, 0x7b, 0xa5, 0x15, 0xd9, 0x22, 0xb2, 0x85, 0x52, 0xfe,
	0xc1, 0xe0, 0x6c, 0xef, 0xef, 0x41, 0x6e, 0x0f, 0x83, 0xd0, 0x50, 0xc2, 0x6b, 0x48, 0xfd, 0x66,
	0x3c, 0xca, 0xe2, 0x62, 0x79, 0xb7, 0x2e, 0xe9, 0x78, 0xa5, 0xaf, 0x14, 0xd3, 0x10, 0xaf, 0x60,
	0x51, 0x69, 0x75, 0xf4, 0x31, 0x31, 0xc5, 0xfc, 0x0a, 0xf8, 0x00, 0xab, 0xf0, 0x47, 0x79, 0x42,
	0x51, 0x97, 0x53, 0x54, 0xb8, 0xab, 0xf8, 0x63, 0x7c, 0x4c, 0x3e, 0xbf, 0xb6, 0xac, 0x4e, 0xe9,
	0x01, 0xee, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0x2a, 0xb9, 0x42, 0xcd, 0xc7, 0x01, 0x00, 0x00,
}
