// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: project_structure.proto

package model

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

// File holds the folder path, children, type, and etcdkey of the given file
type File struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	AbsolutePath         string   `protobuf:"bytes,2,opt,name=absolute_path,json=absolutePath,proto3" json:"absolute_path,omitempty"`
	Type                 string   `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	EtcdKey              string   `protobuf:"bytes,4,opt,name=etcd_key,json=etcdKey,proto3" json:"etcd_key,omitempty"`
	Children             []string `protobuf:"bytes,5,rep,name=children,proto3" json:"children,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *File) Reset()         { *m = File{} }
func (m *File) String() string { return proto.CompactTextString(m) }
func (*File) ProtoMessage()    {}
func (*File) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d2c48c5efc5c804, []int{0}
}
func (m *File) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_File.Unmarshal(m, b)
}
func (m *File) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_File.Marshal(b, m, deterministic)
}
func (m *File) XXX_Merge(src proto.Message) {
	xxx_messageInfo_File.Merge(m, src)
}
func (m *File) XXX_Size() int {
	return xxx_messageInfo_File.Size(m)
}
func (m *File) XXX_DiscardUnknown() {
	xxx_messageInfo_File.DiscardUnknown(m)
}

var xxx_messageInfo_File proto.InternalMessageInfo

func (m *File) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *File) GetAbsolutePath() string {
	if m != nil {
		return m.AbsolutePath
	}
	return ""
}

func (m *File) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *File) GetEtcdKey() string {
	if m != nil {
		return m.EtcdKey
	}
	return ""
}

func (m *File) GetChildren() []string {
	if m != nil {
		return m.Children
	}
	return nil
}

func (*File) XXX_MessageName() string {
	return "model.File"
}

//ProjectStructure holds the directory and folder structure of the project
type ProjectStructure struct {
	File                 []*File  `protobuf:"bytes,1,rep,name=file,proto3" json:"file,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProjectStructure) Reset()         { *m = ProjectStructure{} }
func (m *ProjectStructure) String() string { return proto.CompactTextString(m) }
func (*ProjectStructure) ProtoMessage()    {}
func (*ProjectStructure) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d2c48c5efc5c804, []int{1}
}
func (m *ProjectStructure) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProjectStructure.Unmarshal(m, b)
}
func (m *ProjectStructure) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProjectStructure.Marshal(b, m, deterministic)
}
func (m *ProjectStructure) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProjectStructure.Merge(m, src)
}
func (m *ProjectStructure) XXX_Size() int {
	return xxx_messageInfo_ProjectStructure.Size(m)
}
func (m *ProjectStructure) XXX_DiscardUnknown() {
	xxx_messageInfo_ProjectStructure.DiscardUnknown(m)
}

var xxx_messageInfo_ProjectStructure proto.InternalMessageInfo

func (m *ProjectStructure) GetFile() []*File {
	if m != nil {
		return m.File
	}
	return nil
}

func (*ProjectStructure) XXX_MessageName() string {
	return "model.ProjectStructure"
}
func init() {
	proto.RegisterType((*File)(nil), "model.File")
	proto.RegisterType((*ProjectStructure)(nil), "model.ProjectStructure")
}

func init() { proto.RegisterFile("project_structure.proto", fileDescriptor_5d2c48c5efc5c804) }

var fileDescriptor_5d2c48c5efc5c804 = []byte{
	// 236 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x3c, 0x8f, 0x41, 0x4e, 0xc3, 0x30,
	0x10, 0x45, 0x15, 0xe2, 0x42, 0xeb, 0x82, 0x84, 0xbc, 0xc1, 0x74, 0x01, 0x55, 0xd9, 0x64, 0x43,
	0x2a, 0xd1, 0x1b, 0xb0, 0x60, 0xc3, 0xa6, 0x0a, 0x07, 0x88, 0x12, 0x67, 0x9a, 0x04, 0x9c, 0x8e,
	0xe5, 0x8e, 0x17, 0xb9, 0x02, 0x27, 0xe3, 0x1e, 0x5c, 0x04, 0x79, 0xa2, 0xb2, 0xfb, 0x6f, 0xbe,
	0xbe, 0x34, 0x4f, 0xde, 0x39, 0x8f, 0x9f, 0x60, 0xa8, 0x3c, 0x91, 0x0f, 0x86, 0x82, 0x87, 0xdc,
	0x79, 0x24, 0x54, 0xb3, 0x01, 0x1b, 0xb0, 0xab, 0xe7, 0xb6, 0xa7, 0x2e, 0xd4, 0xb9, 0xc1, 0x61,
	0xdb, 0x62, 0x8b, 0x5b, 0x6e, 0xeb, 0x70, 0x60, 0x62, 0xe0, 0x34, 0xad, 0x36, 0xdf, 0x89, 0x14,
	0x6f, 0xbd, 0x05, 0xa5, 0xa4, 0x38, 0x56, 0x03, 0xe8, 0x64, 0x9d, 0x64, 0x8b, 0x82, 0xb3, 0x7a,
	0x92, 0x37, 0x55, 0x7d, 0x42, 0x1b, 0x08, 0x4a, 0x57, 0x51, 0xa7, 0x2f, 0xb8, 0xbc, 0x3e, 0x1f,
	0xf7, 0x15, 0x75, 0x71, 0x48, 0xa3, 0x03, 0x9d, 0x4e, 0xc3, 0x98, 0xd5, 0xbd, 0x9c, 0x03, 0x99,
	0xa6, 0xfc, 0x82, 0x51, 0x0b, 0xbe, 0x5f, 0x45, 0x7e, 0x87, 0x51, 0xad, 0xe4, 0xdc, 0x74, 0xbd,
	0x6d, 0x3c, 0x1c, 0xf5, 0x6c, 0x9d, 0x66, 0x8b, 0xe2, 0x9f, 0x37, 0x3b, 0x79, 0xbb, 0x9f, 0xec,
	0x3e, 0xce, 0x72, 0xea, 0x51, 0x8a, 0x43, 0x6f, 0xe3, 0x5f, 0x69, 0xb6, 0x7c, 0x59, 0xe6, 0x6c,
	0x99, 0xc7, 0x97, 0x0b, 0x2e, 0x5e, 0xc5, 0xcf, 0xef, 0x43, 0x52, 0x5f, 0xb2, 0xce, 0xee, 0x2f,
	0x00, 0x00, 0xff, 0xff, 0xef, 0xe8, 0xd8, 0xe0, 0x1f, 0x01, 0x00, 0x00,
}
