// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: template_structure.proto

package model

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

// File holds the folder path, children, type, and etcdkey of the given file
type File struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	AbsolutePath         string   `protobuf:"bytes,2,opt,name=absolute_path,json=absolutePath,proto3" json:"absolute_path,omitempty"`
	Type                 string   `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	EtcdKey              string   `protobuf:"bytes,4,opt,name=etcd_key,json=etcdKey,proto3" json:"etcd_key,omitempty"`
	Children             []string `protobuf:"bytes,5,rep,name=children,proto3" json:"children,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *File) Reset()         { *m = File{} }
func (m *File) String() string { return proto.CompactTextString(m) }
func (*File) ProtoMessage()    {}
func (*File) Descriptor() ([]byte, []int) {
	return fileDescriptor_d06b0c468bb01978, []int{0}
}
func (m *File) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_File.Unmarshal(m, b)
}
func (m *File) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_File.Marshal(b, m, deterministic)
}
func (m *File) XXX_Merge(src proto.Message) {
	xxx_messageInfo_File.Merge(m, src)
}
func (m *File) XXX_Size() int {
	return xxx_messageInfo_File.Size(m)
}
func (m *File) XXX_DiscardUnknown() {
	xxx_messageInfo_File.DiscardUnknown(m)
}

var xxx_messageInfo_File proto.InternalMessageInfo

func (m *File) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *File) GetAbsolutePath() string {
	if m != nil {
		return m.AbsolutePath
	}
	return ""
}

func (m *File) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *File) GetEtcdKey() string {
	if m != nil {
		return m.EtcdKey
	}
	return ""
}

func (m *File) GetChildren() []string {
	if m != nil {
		return m.Children
	}
	return nil
}

func (*File) XXX_MessageName() string {
	return "model.File"
}

//TemplateStructure holds the directory and folder structure of the project
type TemplateStructure struct {
	File                 []*File  `protobuf:"bytes,1,rep,name=file,proto3" json:"file,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TemplateStructure) Reset()         { *m = TemplateStructure{} }
func (m *TemplateStructure) String() string { return proto.CompactTextString(m) }
func (*TemplateStructure) ProtoMessage()    {}
func (*TemplateStructure) Descriptor() ([]byte, []int) {
	return fileDescriptor_d06b0c468bb01978, []int{1}
}
func (m *TemplateStructure) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TemplateStructure.Unmarshal(m, b)
}
func (m *TemplateStructure) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TemplateStructure.Marshal(b, m, deterministic)
}
func (m *TemplateStructure) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TemplateStructure.Merge(m, src)
}
func (m *TemplateStructure) XXX_Size() int {
	return xxx_messageInfo_TemplateStructure.Size(m)
}
func (m *TemplateStructure) XXX_DiscardUnknown() {
	xxx_messageInfo_TemplateStructure.DiscardUnknown(m)
}

var xxx_messageInfo_TemplateStructure proto.InternalMessageInfo

func (m *TemplateStructure) GetFile() []*File {
	if m != nil {
		return m.File
	}
	return nil
}

func (*TemplateStructure) XXX_MessageName() string {
	return "model.TemplateStructure"
}
func init() {
	proto.RegisterType((*File)(nil), "model.File")
	proto.RegisterType((*TemplateStructure)(nil), "model.TemplateStructure")
}

func init() { proto.RegisterFile("template_structure.proto", fileDescriptor_d06b0c468bb01978) }

var fileDescriptor_d06b0c468bb01978 = []byte{
	// 236 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x3c, 0x8f, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0x86, 0x15, 0xe2, 0x42, 0x7b, 0x85, 0x01, 0x4f, 0xa6, 0x03, 0x54, 0x65, 0xc9, 0x42, 0x2a,
	0x01, 0x4f, 0xc0, 0xc0, 0xc2, 0x82, 0x02, 0x7b, 0xe4, 0x24, 0xd7, 0x24, 0xc2, 0xa9, 0x2d, 0xf7,
	0x3c, 0xe4, 0x15, 0x78, 0x32, 0xde, 0x83, 0x17, 0x41, 0xbe, 0x92, 0x6e, 0xff, 0x77, 0xbf, 0x7e,
	0xe9, 0x3e, 0x50, 0x84, 0x83, 0x33, 0x9a, 0xb0, 0x3c, 0x90, 0x0f, 0x35, 0x05, 0x8f, 0xb9, 0xf3,
	0x96, 0xac, 0x9c, 0x0d, 0xb6, 0x41, 0xb3, 0x7a, 0x68, 0x7b, 0xea, 0x42, 0x95, 0xd7, 0x76, 0xd8,
	0xb6, 0xb6, 0xb5, 0x5b, 0x6e, 0xab, 0xb0, 0x63, 0x62, 0xe0, 0x74, 0x5c, 0x6d, 0xbe, 0x13, 0x10,
	0xaf, 0xbd, 0x41, 0x29, 0x41, 0xec, 0xf5, 0x80, 0x2a, 0x59, 0x27, 0xd9, 0xa2, 0xe0, 0x2c, 0xef,
	0xe1, 0x4a, 0x57, 0x07, 0x6b, 0x02, 0x61, 0xe9, 0x34, 0x75, 0xea, 0x8c, 0xcb, 0xcb, 0xe9, 0xf8,
	0xae, 0xa9, 0x8b, 0x43, 0x1a, 0x1d, 0xaa, 0xf4, 0x38, 0x8c, 0x59, 0xde, 0xc0, 0x1c, 0xa9, 0x6e,
	0xca, 0x2f, 0x1c, 0x95, 0xe0, 0xfb, 0x45, 0xe4, 0x37, 0x1c, 0xe5, 0x0a, 0xe6, 0x75, 0xd7, 0x9b,
	0xc6, 0xe3, 0x5e, 0xcd, 0xd6, 0x69, 0xb6, 0x28, 0x4e, 0xbc, 0x79, 0x86, 0xeb, 0xcf, 0x7f, 0xbd,
	0x8f, 0xc9, 0x4e, 0xde, 0x81, 0xd8, 0xf5, 0x26, 0x3e, 0x96, 0x66, 0xcb, 0xc7, 0x65, 0xce, 0x9a,
	0x79, 0xfc, 0xb9, 0xe0, 0xe2, 0x45, 0xfc, 0xfc, 0xde, 0x26, 0xd5, 0x39, 0xfb, 0x3c, 0xfd, 0x05,
	0x00, 0x00, 0xff, 0xff, 0x16, 0x1c, 0xd4, 0xf2, 0x21, 0x01, 0x00, 0x00,
}
