// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: template_structure.proto

package model

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

// FileContent holds the content of the go file
type FileContent struct {
	// Content of the generated code file
	Content              string   `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileContent) Reset()         { *m = FileContent{} }
func (m *FileContent) String() string { return proto.CompactTextString(m) }
func (*FileContent) ProtoMessage()    {}
func (*FileContent) Descriptor() ([]byte, []int) {
	return fileDescriptor_d06b0c468bb01978, []int{0}
}
func (m *FileContent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileContent.Unmarshal(m, b)
}
func (m *FileContent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileContent.Marshal(b, m, deterministic)
}
func (m *FileContent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileContent.Merge(m, src)
}
func (m *FileContent) XXX_Size() int {
	return xxx_messageInfo_FileContent.Size(m)
}
func (m *FileContent) XXX_DiscardUnknown() {
	xxx_messageInfo_FileContent.DiscardUnknown(m)
}

var xxx_messageInfo_FileContent proto.InternalMessageInfo

func (m *FileContent) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (*FileContent) XXX_MessageName() string {
	return "model.FileContent"
}

// File holds the folder path, children, type, and etcdkey of the given file
type File struct {
	// Name of generated code file or folder
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Path of generated code file
	AbsolutePath string `protobuf:"bytes,2,opt,name=absolutePath,proto3" json:"absolutePath,omitempty"`
	// "Folder" if a folder in the directory or "File" if code file
	FileType string `protobuf:"bytes,3,opt,name=fileType,proto3" json:"fileType,omitempty"`
	// Key the file is stored under in etcd
	EtcdKey string `protobuf:"bytes,4,opt,name=etcdKey,proto3" json:"etcdKey,omitempty"`
	// Absolute path(s) of direct children folders of the file, empty list if no children
	Children             []string `protobuf:"bytes,5,rep,name=children,proto3" json:"children,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *File) Reset()         { *m = File{} }
func (m *File) String() string { return proto.CompactTextString(m) }
func (*File) ProtoMessage()    {}
func (*File) Descriptor() ([]byte, []int) {
	return fileDescriptor_d06b0c468bb01978, []int{1}
}
func (m *File) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_File.Unmarshal(m, b)
}
func (m *File) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_File.Marshal(b, m, deterministic)
}
func (m *File) XXX_Merge(src proto.Message) {
	xxx_messageInfo_File.Merge(m, src)
}
func (m *File) XXX_Size() int {
	return xxx_messageInfo_File.Size(m)
}
func (m *File) XXX_DiscardUnknown() {
	xxx_messageInfo_File.DiscardUnknown(m)
}

var xxx_messageInfo_File proto.InternalMessageInfo

func (m *File) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *File) GetAbsolutePath() string {
	if m != nil {
		return m.AbsolutePath
	}
	return ""
}

func (m *File) GetFileType() string {
	if m != nil {
		return m.FileType
	}
	return ""
}

func (m *File) GetEtcdKey() string {
	if m != nil {
		return m.EtcdKey
	}
	return ""
}

func (m *File) GetChildren() []string {
	if m != nil {
		return m.Children
	}
	return nil
}

func (*File) XXX_MessageName() string {
	return "model.File"
}

//TemplateStructure holds the directory and folder structure of the project
type TemplateStructure struct {
	// List of file objects describing directory structure of generated files
	File                 []*File  `protobuf:"bytes,1,rep,name=file,proto3" json:"file,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TemplateStructure) Reset()         { *m = TemplateStructure{} }
func (m *TemplateStructure) String() string { return proto.CompactTextString(m) }
func (*TemplateStructure) ProtoMessage()    {}
func (*TemplateStructure) Descriptor() ([]byte, []int) {
	return fileDescriptor_d06b0c468bb01978, []int{2}
}
func (m *TemplateStructure) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TemplateStructure.Unmarshal(m, b)
}
func (m *TemplateStructure) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TemplateStructure.Marshal(b, m, deterministic)
}
func (m *TemplateStructure) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TemplateStructure.Merge(m, src)
}
func (m *TemplateStructure) XXX_Size() int {
	return xxx_messageInfo_TemplateStructure.Size(m)
}
func (m *TemplateStructure) XXX_DiscardUnknown() {
	xxx_messageInfo_TemplateStructure.DiscardUnknown(m)
}

var xxx_messageInfo_TemplateStructure proto.InternalMessageInfo

func (m *TemplateStructure) GetFile() []*File {
	if m != nil {
		return m.File
	}
	return nil
}

func (*TemplateStructure) XXX_MessageName() string {
	return "model.TemplateStructure"
}
func init() {
	proto.RegisterType((*FileContent)(nil), "model.FileContent")
	proto.RegisterType((*File)(nil), "model.File")
	proto.RegisterType((*TemplateStructure)(nil), "model.TemplateStructure")
}

func init() { proto.RegisterFile("template_structure.proto", fileDescriptor_d06b0c468bb01978) }

var fileDescriptor_d06b0c468bb01978 = []byte{
	// 249 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0x3d, 0x4e, 0xc4, 0x30,
	0x10, 0x85, 0x65, 0xe2, 0xe5, 0x67, 0x42, 0x83, 0x2b, 0x6b, 0x0b, 0x88, 0xd2, 0xb0, 0x0d, 0x59,
	0x09, 0x38, 0x01, 0x48, 0x34, 0x34, 0x68, 0xd9, 0x1e, 0x25, 0xce, 0x6c, 0x12, 0xc9, 0x89, 0xa3,
	0xec, 0xb8, 0xc8, 0x2d, 0x38, 0x16, 0xf7, 0xe0, 0x22, 0xc8, 0x93, 0x04, 0x69, 0xbb, 0xf7, 0xf9,
	0xf9, 0x79, 0x3c, 0x0f, 0x34, 0x61, 0xdb, 0xdb, 0x9c, 0xf0, 0xeb, 0x48, 0x83, 0x37, 0xe4, 0x07,
	0xcc, 0xfa, 0xc1, 0x91, 0x53, 0xab, 0xd6, 0x95, 0x68, 0xd7, 0x0f, 0x55, 0x43, 0xb5, 0x2f, 0x32,
	0xe3, 0xda, 0x6d, 0xe5, 0x2a, 0xb7, 0x65, 0xb7, 0xf0, 0x07, 0x26, 0x06, 0x56, 0x53, 0x2a, 0xbd,
	0x87, 0xf8, 0xad, 0xb1, 0xf8, 0xea, 0x3a, 0xc2, 0x8e, 0x94, 0x86, 0x0b, 0x33, 0x49, 0x2d, 0x12,
	0xb1, 0xb9, 0xda, 0x2d, 0x98, 0x7e, 0x0b, 0x90, 0xe1, 0xa6, 0x52, 0x20, 0xbb, 0xbc, 0xc5, 0xd9,
	0x67, 0xad, 0x52, 0xb8, 0xce, 0x8b, 0xa3, 0xb3, 0x9e, 0xf0, 0x23, 0xa7, 0x5a, 0x9f, 0xb1, 0x77,
	0x72, 0xa6, 0xd6, 0x70, 0x79, 0x68, 0x2c, 0xee, 0xc7, 0x1e, 0x75, 0xc4, 0xfe, 0x3f, 0x87, 0xb1,
	0x48, 0xa6, 0x7c, 0xc7, 0x51, 0xcb, 0x69, 0xec, 0x8c, 0x21, 0x65, 0xea, 0xc6, 0x96, 0x03, 0x76,
	0x7a, 0x95, 0x44, 0x21, 0xb5, 0x70, 0xfa, 0x0c, 0x37, 0xfb, 0xb9, 0x8d, 0xcf, 0xa5, 0x0c, 0x75,
	0x07, 0x32, 0x3c, 0xab, 0x45, 0x12, 0x6d, 0xe2, 0xc7, 0x38, 0xe3, 0x56, 0xb2, 0xf0, 0xf3, 0x1d,
	0x1b, 0x2f, 0xf2, 0xe7, 0xf7, 0x56, 0x14, 0xe7, 0xbc, 0xfe, 0xd3, 0x5f, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x87, 0xb1, 0xd0, 0x59, 0x50, 0x01, 0x00, 0x00,
}
