export const ADD_CURR_PROJECT = "ADD_CURR_PROJECT";
export const SET_CURR_PROJECT = "SET_CURR_PROJECT";
export const SET_CURR_POPUP_ID = "SET_CURR_POPUP_ID";
export const SAVE_PROJECT = "SAVE_PROJECT";
export const LOAD_PROJECT = "LOAD_PROJECT";
export const RETURN_LOAD_PROJECT = "RETURN_LOAD_PROJECT";
export const GENERATE_CURR_PROJECT = "GENERATE_CURR_PROJECT";
export const DELIVER_GENERATED_TAR = "DELIVER_GENERATED_TAR";