// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: rest_template_structure.proto

package model

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

// FileContent holds the content of the go file
type FileContent struct {
	Content              string   `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileContent) Reset()         { *m = FileContent{} }
func (m *FileContent) String() string { return proto.CompactTextString(m) }
func (*FileContent) ProtoMessage()    {}
func (*FileContent) Descriptor() ([]byte, []int) {
	return fileDescriptor_e578eed11d4f8452, []int{0}
}
func (m *FileContent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileContent.Unmarshal(m, b)
}
func (m *FileContent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileContent.Marshal(b, m, deterministic)
}
func (m *FileContent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileContent.Merge(m, src)
}
func (m *FileContent) XXX_Size() int {
	return xxx_messageInfo_FileContent.Size(m)
}
func (m *FileContent) XXX_DiscardUnknown() {
	xxx_messageInfo_FileContent.DiscardUnknown(m)
}

var xxx_messageInfo_FileContent proto.InternalMessageInfo

func (m *FileContent) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (*FileContent) XXX_MessageName() string {
	return "model.FileContent"
}

// File holds the folder path, children, type, and etcdkey of the given file
type File struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	AbsolutePath         string   `protobuf:"bytes,2,opt,name=absolute_path,json=absolutePath,proto3" json:"absolute_path,omitempty"`
	FileType             string   `protobuf:"bytes,3,opt,name=fileType,proto3" json:"fileType,omitempty"`
	EtcdKey              string   `protobuf:"bytes,4,opt,name=etcdKey,proto3" json:"etcdKey,omitempty"`
	Children             []string `protobuf:"bytes,5,rep,name=children,proto3" json:"children,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *File) Reset()         { *m = File{} }
func (m *File) String() string { return proto.CompactTextString(m) }
func (*File) ProtoMessage()    {}
func (*File) Descriptor() ([]byte, []int) {
	return fileDescriptor_e578eed11d4f8452, []int{1}
}
func (m *File) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_File.Unmarshal(m, b)
}
func (m *File) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_File.Marshal(b, m, deterministic)
}
func (m *File) XXX_Merge(src proto.Message) {
	xxx_messageInfo_File.Merge(m, src)
}
func (m *File) XXX_Size() int {
	return xxx_messageInfo_File.Size(m)
}
func (m *File) XXX_DiscardUnknown() {
	xxx_messageInfo_File.DiscardUnknown(m)
}

var xxx_messageInfo_File proto.InternalMessageInfo

func (m *File) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *File) GetAbsolutePath() string {
	if m != nil {
		return m.AbsolutePath
	}
	return ""
}

func (m *File) GetFileType() string {
	if m != nil {
		return m.FileType
	}
	return ""
}

func (m *File) GetEtcdKey() string {
	if m != nil {
		return m.EtcdKey
	}
	return ""
}

func (m *File) GetChildren() []string {
	if m != nil {
		return m.Children
	}
	return nil
}

func (*File) XXX_MessageName() string {
	return "model.File"
}

//TemplateStructure holds the directory and folder structure of the project
type TemplateStructure struct {
	File                 []*File  `protobuf:"bytes,1,rep,name=file,proto3" json:"file,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TemplateStructure) Reset()         { *m = TemplateStructure{} }
func (m *TemplateStructure) String() string { return proto.CompactTextString(m) }
func (*TemplateStructure) ProtoMessage()    {}
func (*TemplateStructure) Descriptor() ([]byte, []int) {
	return fileDescriptor_e578eed11d4f8452, []int{2}
}
func (m *TemplateStructure) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TemplateStructure.Unmarshal(m, b)
}
func (m *TemplateStructure) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TemplateStructure.Marshal(b, m, deterministic)
}
func (m *TemplateStructure) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TemplateStructure.Merge(m, src)
}
func (m *TemplateStructure) XXX_Size() int {
	return xxx_messageInfo_TemplateStructure.Size(m)
}
func (m *TemplateStructure) XXX_DiscardUnknown() {
	xxx_messageInfo_TemplateStructure.DiscardUnknown(m)
}

var xxx_messageInfo_TemplateStructure proto.InternalMessageInfo

func (m *TemplateStructure) GetFile() []*File {
	if m != nil {
		return m.File
	}
	return nil
}

func (*TemplateStructure) XXX_MessageName() string {
	return "model.TemplateStructure"
}
func init() {
	proto.RegisterType((*FileContent)(nil), "model.FileContent")
	proto.RegisterType((*File)(nil), "model.File")
	proto.RegisterType((*TemplateStructure)(nil), "model.TemplateStructure")
}

func init() { proto.RegisterFile("rest_template_structure.proto", fileDescriptor_e578eed11d4f8452) }

var fileDescriptor_e578eed11d4f8452 = []byte{
	// 256 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x3c, 0x90, 0xcd, 0x4e, 0x84, 0x30,
	0x14, 0x85, 0x83, 0x74, 0xfc, 0x29, 0xba, 0xb0, 0xab, 0x66, 0x12, 0x95, 0xe0, 0xc2, 0xd9, 0xc8,
	0x24, 0xea, 0x13, 0x68, 0xe2, 0xc6, 0x8d, 0x19, 0x67, 0x4f, 0x4a, 0xb9, 0x03, 0x24, 0x85, 0x92,
	0x72, 0xbb, 0x98, 0xc7, 0xf0, 0xad, 0x7c, 0x0f, 0x5f, 0xc4, 0xf4, 0x02, 0xee, 0xce, 0xd7, 0xd3,
	0xd3, 0xdb, 0x7b, 0xf8, 0x8d, 0x83, 0x11, 0x0b, 0x84, 0x6e, 0x30, 0x0a, 0xa1, 0x18, 0xd1, 0x79,
	0x8d, 0xde, 0x41, 0x3e, 0x38, 0x8b, 0x56, 0xac, 0x3a, 0x5b, 0x81, 0x59, 0x3f, 0xd6, 0x2d, 0x36,
	0xbe, 0xcc, 0xb5, 0xed, 0xb6, 0xb5, 0xad, 0xed, 0x96, 0xdc, 0xd2, 0x1f, 0x88, 0x08, 0x48, 0x4d,
	0xa9, 0xec, 0x81, 0x27, 0xef, 0xad, 0x81, 0x37, 0xdb, 0x23, 0xf4, 0x28, 0x24, 0x3f, 0xd3, 0x93,
	0x94, 0x51, 0x1a, 0x6d, 0x2e, 0x76, 0x0b, 0x66, 0xdf, 0x11, 0x67, 0xe1, 0xa6, 0x10, 0x9c, 0xf5,
	0xaa, 0x83, 0xd9, 0x27, 0x2d, 0xee, 0xf9, 0x95, 0x2a, 0x47, 0x6b, 0x3c, 0x42, 0x31, 0x28, 0x6c,
	0xe4, 0x09, 0x99, 0x97, 0xcb, 0xe1, 0xa7, 0xc2, 0x46, 0xac, 0xf9, 0xf9, 0xa1, 0x35, 0xb0, 0x3f,
	0x0e, 0x20, 0x63, 0xf2, 0xff, 0x39, 0xcc, 0x05, 0xd4, 0xd5, 0x07, 0x1c, 0x25, 0x9b, 0xe6, 0xce,
	0x18, 0x52, 0xba, 0x69, 0x4d, 0xe5, 0xa0, 0x97, 0xab, 0x34, 0x0e, 0xa9, 0x85, 0xb3, 0x17, 0x7e,
	0xbd, 0x9f, 0xeb, 0xf8, 0x5a, 0xda, 0x10, 0x77, 0x9c, 0x85, 0x67, 0x65, 0x94, 0xc6, 0x9b, 0xe4,
	0x29, 0xc9, 0xa9, 0x96, 0x3c, 0x7c, 0x7d, 0x47, 0xc6, 0x2b, 0xfb, 0xf9, 0xbd, 0x8d, 0xca, 0x53,
	0xda, 0xff, 0xf9, 0x2f, 0x00, 0x00, 0xff, 0xff, 0xea, 0x67, 0x61, 0xb5, 0x56, 0x01, 0x00, 0x00,
}
