/*** This is an autogenerated file; This file can be edited but changes should be saved***/

package main

import (
    "github.com/ligato/cn-infra/agent"
    "github.com/ligato/cn-infra/logging"
    log "github.com/ligato/cn-infra/logging/logrus"
    "github.com/ligato/cn-infra/db/keyval/redis"
)

// untitled is a struct holding internal data for the untitled Agent
type untitled struct {
    Redis    *redis.Plugin
}

// New creates new untitled instance.
func New() *untitled {
    return &untitled {
        Redis:    &redis.DefaultPlugin,
    }
}

// Init initializes main plugin.
func (pr *untitled) Init() error {
    return nil
}

func (pr *untitled) AfterInit() error {
    resync.DefaultPlugin.DoResync()
    return nil
}

// Close can be used to close used resources.
func (pr *untitled) Close() error {
    return nil
}

// String returns name of the plugin.
func (pr *untitled) String() string {
    return "untitled"
}

func main() {
    untitled := New()

    a := agent.NewAgent(agent.AllPlugins(untitled))

    if err := a.Run(); err != nil {
        log.DefaultLogger().Fatal(err)
    }
}

func init() {
	log.DefaultLogger().SetOutput(os.Stdout)
	log.DefaultLogger().SetLevel(logging.DebugLevel)
}